version: 2.1
      
orbs:
  snyk: snyk/snyk@1.4.0
  
jobs:
  main:
    parameters:
      image: 
        type: string
      circle_pr_number:
        type: string
        default: $CIRCLE_PR_NUMBER
    
    docker: 
      - image: <<parameters.image>>
    
    # Add resource_class to increase available memory
    resource_class: large

    steps: 
      - checkout
      # Add environment variables to help with memory management
      - run:
          command: |
            echo "export MAKEFLAGS=-j2" >> $BASH_ENV
            echo "export NPY_NUM_BUILD_JOBS=2" >> $BASH_ENV
            source $BASH_ENV
      # Install numpy separately first
      - run:
          command: pip install numpy==1.26.4
          no_output_timeout: 30m
      - run: poetry install --no-ansi
      - unless:
          condition: << parameters.circle_pr_number >>
          steps:
            - snyk/scan
      - run: poetry run pytest
      - run: poetry run flake8

workflows:
  build:
    jobs:
      - main:
          matrix:
            parameters:
              image: [
                # "cimg/python:3.9",
                # "cimg/python:3.10",
                # "cimg/python:3.11",
                # "cimg/python:3.12",
                "cimg/python:3.13"
              ]
     